config/routes.rb
Job::Application.routes.draw do
  devise_for :users#, :skip => :all

  resources :listings
  
  resources :messages
  
  match 'messages/:id/new' => 'messages#new', :as => :new_message
  
  
  match "/my_messages" => "messages#index_by_current_user"
  
  get "home/index"
 
  root :to => "home#index"
  
   

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  
  has_many :messages
  belongs_to :user

    validates :title,  :presence => true
    validates :company, :presence => true
    validates :description, :presence => true
    validates :user_id, :presence => true
    
end

app/models/message.rb
class Message < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :listing
  
  validates :message,  :presence => true
  
end

app/models/user.rb
class User < ActiveRecord::Base  
  
  has_many  :listings
  has_many :messages
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
  before_filter :authenticate_user!, :except => [:index, :show]
  
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @listing }
    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = Listing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(params[:listing])
    #Adding the user via the devise current_user user object. Validation should catch it if somehow this is nil
    @listing.user = current_user
    
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, :notice => 'Listing was successfully created.' }
        format.json { render :json => @listing, :status => :created, :location => @listing }
      else
        format.html { render :action => "new" }
        format.json { render :json => @listing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to @listing, :notice => 'Listing was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @listing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :ok }
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

   before_filter :authenticate_user!

    def index
      #this action should be removed perhaps or only allowed for super users or something
      @messages = Message.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @messages }
      end
    end
    
    def new
      
      @message = Message.new
      #There should always be a listing with a Message, so go get it. 
      #TODO: is this safe.... 
      @listing = Listing.find(params[:id])
      session[:listing] = @listing
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @listing }
      end
    end
    
    def index_by_current_user
      #This will be used to create an "inbox" where a job poster can view his jobs
      @listings = Listing.find(:all, :conditions => ["user_id = ?", current_user.id])
      @messages = Array.new
      @listings.each do | listings |
        listings.messages.each do |message|
          @messages << message
        end
      end  
      
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @messages }
      end
      
    end

    def show
      @message = Message.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @message }
      end
    end
    
    
    def create
      #TODO: fix this.. hack. should just pass a different param.
      @message = Message.new(params[:message])
      @message.listing = session[:listing]
      #Adding the user via the devise current_user user object. Validation should catch it if somehow this is nil
      @message.user = current_user

      respond_to do |format|
        if @message.save
          format.html { redirect_to listings_path, :notice => 'Message was successfully created.' }
          format.json { render :json => @message, :status => :created, :location => @message }
        else
          format.html { render :action => "new" }
          format.json { render :json => @message.errors, :status => :unprocessable_entity }
        end
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  #This code is all taken from http://blog.plataformatec.com.br/tag/devise/
  # For security purposes, Devise just authenticates an user
  # from the params hash if we explicitly allow it to. That's
  # why we need to call the before filter below.
  before_filter :allow_params_authentication!, :only => :create
 
  def new
    @user = User.new(params[:user])
  end
 
  def create
    # Since the authentication happens in the rack layer,
    # we need to tell Devise to call the action "sessions#new"
    # in case something goes bad. Feel free to change it.
    user = authenticate_user!(:recall => "sessions#new")
    flash[:notice] = "You are now signed in!"
    sign_in user
    redirect_to root_path
  end
 
  def destroy
    sign_out
    flash[:notice] = "You are now signed out!"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/index.html.erb
<h1>Welcome to Jobs</h1>
<p>This is a small example app I was asked to create, the code is hosted on Github user https://github.com/ramen74/job</p>
<p>This project is created on Rails 3.1</p>
<p> Here's what you can do here </p>

<ul>
	
<li><%= link_to "View and Apply for Jobs", listings_path %> </li>
<li><%= link_to "Create A New Job Listing", new_listing_path %> </li>
<li><%= link_to "Check on your listings", my_messages_path %> </li>

</ul>

<div id="about_project">
<p>Here's the requirements for this project!:</p>
<ul>
<li>Viewing the jobs does not require logging in, but posting or responding does.</li>
<li>A user needs to register to be able to sign in.</li>
<li>A user has a name and an email address, and a password.</li>
<li>A logged-in user can create a job posting and /edit/delete these.</li>
<li>A job posting has a title, a company, a description.</li>
<li>A logged-in user can respond to a job which provides a message to the job creator in a simple inbox format.</li>
<li>Unit tests.</li>
</ul>

<p> Enjoy! </p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Job</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="user_nav">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>. Not you?
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
  <% end %>
</div>

    

<%= yield %>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>


  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

   
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>

<table>
  <tr>
	<th></th>
    <th>Title</th>
    <th>Company</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @listings.each do |listing| %>
  <tr>	
	<td><%= link_to 'Apply', new_message_path([listing.id]) %>
    <td><%= listing.title %></td>
    <td><%= listing.company %></td>
    <td><%= listing.description %></td>

    <td><%= link_to 'Show', listing %></td>
    <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
    <td><%= link_to 'Destroy', listing, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @listing.title %>
</p>

<p>
  <b>Company:</b>
  <%= @listing.company %>
</p>

<p>
  <b>Description:</b>
  <%= @listing.description %>
</p>

<p>
  <b>Created by:</b>
  <%= @listing.user.email %>
</p>


<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>

  Thanks for applying for <%= @listing.description %> </br></br> 

  <div class="field">
    <%= f.label :tell_us_about_yourself %><br />
    <%= f.text_area :message %>
  </div>
     
  <%#= f.hidden_field (:listing, :value => @listing.id) %>
	
  <div class="actions">
    <%= f.submit %>
  </div>
<%- end %>

app/views/messages/index.html.erb
<h1>Message messages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Company</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @messages.each do |message| %>
  <tr>
    <td><%= message.title %></td>
    <td><%= message.company %></td>
    <td><%= message.description %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message', new_message_path %>

app/views/messages/index_by_current_user.html.erb
<h1>Your Messages</h1>

  <table>
    <tr>
      <th>Listing </th>
      <th>From </th>
      <th>Message </th>
    </tr>

  <%- @messages.each do |message| %>
    <tr>
      <td><%= message.listing.title  %></td>
      <td><%= message.user.email %></td>
      <td><%= message.message %></td>
    </tr>
  <%- end %>
  </table>

  <br />


<%= link_to 'Back to listings', listings_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>